spring: 
  profiles:
    active: dev
    
---
#开发环境dev
spring: 
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3309/db_hotel?useSSL=false
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
name: devddd
---
#测试环境
spring: 
  profiles: test
name: testdfdf
---
#生产环境pro
spring: 
  profiles: pro
name: proddd
